import { Track } from './store'

export const mockTracks: Track[] = [
  {
    id: '1',
    title: 'Neon Dreams',
    artist: 'AI Composer',
    cover: 'https://picsum.photos/seed/neon/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    duration: 210,
    genre: 'Synthwave',
    prompt: 'A retro synthwave track with dreamy pads and pulsing bass',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    title: 'Summer Vibes',
    artist: 'AI Composer',
    cover: 'https://picsum.photos/seed/summer/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    duration: 185,
    genre: 'Pop',
    prompt: 'An upbeat summer pop song with catchy melody',
    createdAt: new Date('2024-01-14'),
  },
  {
    id: '3',
    title: 'Midnight Jazz',
    artist: 'AI Composer',
    cover: 'https://picsum.photos/seed/jazz/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    duration: 245,
    genre: 'Jazz',
    prompt: 'A smooth jazz piece perfect for late night',
    createdAt: new Date('2024-01-13'),
  },
  {
    id: '4',
    title: 'Epic Adventure',
    artist: 'AI Composer',
    cover: 'https://picsum.photos/seed/epic/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    duration: 320,
    genre: 'Cinematic',
    prompt: 'An epic orchestral piece for a hero journey',
    createdAt: new Date('2024-01-12'),
  },
  {
    id: '5',
    title: 'Lo-Fi Study',
    artist: 'AI Composer',
    cover: 'https://picsum.photos/seed/lofi/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    duration: 195,
    genre: 'Lo-Fi',
    prompt: 'Chill lo-fi beats to study and relax',
    createdAt: new Date('2024-01-11'),
  },
  {
    id: '6',
    title: 'Electronic Pulse',
    artist: 'AI Composer',
    cover: 'https://picsum.photos/seed/electronic/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    duration: 225,
    genre: 'Electronic',
    prompt: 'High energy electronic dance track',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '7',
    title: 'Acoustic Morning',
    artist: 'AI Composer',
    cover: 'https://picsum.photos/seed/acoustic/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    duration: 180,
    genre: 'Acoustic',
    prompt: 'A gentle acoustic guitar piece for morning',
    createdAt: new Date('2024-01-09'),
  },
  {
    id: '8',
    title: 'Hip Hop Beat',
    artist: 'AI Composer',
    cover: 'https://picsum.photos/seed/hiphop/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    duration: 200,
    genre: 'Hip Hop',
    prompt: 'A groovy hip hop beat with heavy bass',
    createdAt: new Date('2024-01-08'),
  },
]

export const samplePrompts = [
  'Make a house song about quitting your job',
  'A sad piano ballad about lost love',
  'Upbeat K-pop track with catchy chorus',
  'Epic cinematic music for a space battle',
  'Chill lo-fi beats for studying',
  'Rock anthem about freedom',
  'Jazz fusion with electronic elements',
  'Country song about summer nights',
]
